# Generated by Django 5.2.17 on 2026-09-03 02:31

import django.core.validators
import django.db.models.deletion
import properties.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalRule',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('trade_type', models.CharField(choices=[('sale', '매매')], default='sale', max_length=16, verbose_name='거래 유형')),
                ('low_floor_numeric_floors', models.JSONField(default=properties.models._default_low_floor_numbers, validators=[properties.models._validate_int_list], verbose_name='저층 숫자')),
                ('low_floor_labels', models.JSONField(default=properties.models._default_low_floor_labels, validators=[properties.models._validate_string_list], verbose_name='저층 표기')),
                ('low_floor_price_discount_won', models.PositiveBigIntegerField(default=100000000, verbose_name='저층 가격 차감액')),
                ('timezone', models.CharField(default='Asia/Seoul', max_length=64, validators=[properties.models._validate_timezone], verbose_name='시간대')),
                ('digest_weekdays', models.JSONField(default=properties.models._default_digest_weekdays, validators=[properties.models._validate_weekdays], verbose_name='정기 보고 요일')),
                ('digest_hour', models.PositiveSmallIntegerField(default=8, validators=[django.core.validators.MaxValueValidator(23)], verbose_name='정기 보고 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
            ],
            options={
                'verbose_name': '공통 규칙',
                'verbose_name_plural': '공통 규칙',
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(db_index=True, verbose_name='시작 시각')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='종료 시각')),
                ('success', models.BooleanField(default=False, verbose_name='성공')),
                ('successful_conditions', models.JSONField(default=list, verbose_name='성공 조건')),
                ('failed_conditions', models.JSONField(default=dict, verbose_name='실패 조건')),
                ('collected_count', models.PositiveIntegerField(default=0, verbose_name='수집 수')),
                ('matched_count', models.PositiveIntegerField(default=0, verbose_name='조건 충족 수')),
                ('urgent_count', models.PositiveIntegerField(default=0, verbose_name='급매 수')),
                ('excluded_count', models.PositiveIntegerField(default=0, verbose_name='제외 수')),
                ('notification', models.TextField(blank=True, verbose_name='알림 결과 또는 미전송 사유')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='기록 시각')),
            ],
            options={
                'verbose_name': '수집 실행',
                'verbose_name_plural': '수집 실행',
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='NotificationFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='메시지')),
                ('link_url', models.URLField(blank=True, max_length=2048, verbose_name='링크 URL')),
                ('error', models.TextField(verbose_name='오류')),
                ('attempts', models.PositiveIntegerField(default=1, verbose_name='시도 횟수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='발생 시각')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='마지막 시도 시각')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='처리 완료 시각')),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_failures', to='properties.scan', verbose_name='수집 실행')),
            ],
            options={
                'verbose_name': '알림 실패',
                'verbose_name_plural': '알림 실패',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SearchCondition',
            fields=[
                ('id', models.SlugField(max_length=100, primary_key=True, serialize=False, verbose_name='조건 ID')),
                ('name', models.CharField(max_length=200, verbose_name='이름')),
                ('complex_names', models.JSONField(default=list, validators=[properties.models._validate_string_list], verbose_name='단지명 별칭')),
                ('search_url', models.URLField(blank=True, max_length=2048, verbose_name='검색 URL')),
                ('exclusive_area_m2', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='기준 전용면적(㎡)')),
                ('exclusive_area_min_m2', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='최소 전용면적(㎡)')),
                ('exclusive_area_max_m2', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='최대 전용면적(㎡)')),
                ('allowed_types', models.JSONField(blank=True, null=True, validators=[properties.models._validate_string_list], verbose_name='허용 타입')),
                ('max_price_won', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='조사 상한가')),
                ('urgent_price_won', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='급매 기준가')),
                ('notify_new', models.BooleanField(default=False, verbose_name='신규 매물 알림')),
                ('apply_low_floor_discount', models.BooleanField(default=True, verbose_name='저층 차감 적용')),
                ('enabled', models.BooleanField(default=True, verbose_name='사용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
            ],
            options={
                'verbose_name': '검색 조건',
                'verbose_name_plural': '검색 조건',
                'ordering': ('name',),
                'constraints': [models.CheckConstraint(condition=models.Q(('max_price_won__isnull', True), ('urgent_price_won__isnull', True), ('urgent_price_won__lte', models.F('max_price_won')), _connector='OR'), name='urgent_price_not_above_max'), models.CheckConstraint(condition=models.Q(('exclusive_area_min_m2__isnull', True), ('exclusive_area_max_m2__isnull', True), ('exclusive_area_min_m2__lte', models.F('exclusive_area_max_m2')), _connector='OR'), name='area_min_not_above_max')],
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.CharField(max_length=100, verbose_name='매물 ID')),
                ('complex_name', models.CharField(max_length=255, verbose_name='단지명')),
                ('type_name', models.CharField(blank=True, max_length=100, verbose_name='타입')),
                ('exclusive_area_m2', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='전용면적(㎡)')),
                ('price_won', models.PositiveBigIntegerField(verbose_name='가격')),
                ('floor_text', models.CharField(blank=True, max_length=100, verbose_name='층')),
                ('floor', models.IntegerField(blank=True, null=True, verbose_name='숫자 층')),
                ('direction', models.CharField(blank=True, max_length=100, verbose_name='방향')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('url', models.URLField(blank=True, max_length=2048, verbose_name='원본 URL')),
                ('observed_at', models.DateTimeField(db_index=True, verbose_name='관측 시각')),
                ('is_low_floor', models.BooleanField(default=False, verbose_name='저층')),
                ('effective_max_price_won', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='적용 조사 상한가')),
                ('effective_urgent_price_won', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='적용 급매 기준가')),
                ('exclusion_reason', models.TextField(blank=True, verbose_name='제외 사유')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='수집 원본')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='properties.scan', verbose_name='수집 실행')),
                ('condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='properties.searchcondition', verbose_name='검색 조건')),
            ],
            options={
                'verbose_name': '수집 원본',
                'verbose_name_plural': '수집 원본',
                'ordering': ('-observed_at', 'listing_id'),
                'indexes': [models.Index(fields=['scan', 'condition'], name='properties__scan_id_0c86f5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.CharField(max_length=100, verbose_name='매물 ID')),
                ('complex_name', models.CharField(max_length=255, verbose_name='단지명')),
                ('type_name', models.CharField(blank=True, max_length=100, verbose_name='타입')),
                ('exclusive_area_m2', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='전용면적(㎡)')),
                ('price_won', models.PositiveBigIntegerField(verbose_name='가격')),
                ('floor_text', models.CharField(blank=True, max_length=100, verbose_name='층')),
                ('floor', models.IntegerField(blank=True, null=True, verbose_name='숫자 층')),
                ('direction', models.CharField(blank=True, max_length=100, verbose_name='방향')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('url', models.URLField(blank=True, max_length=2048, verbose_name='원본 URL')),
                ('observed_at', models.DateTimeField(db_index=True, verbose_name='관측 시각')),
                ('is_low_floor', models.BooleanField(default=False, verbose_name='저층')),
                ('effective_max_price_won', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='적용 조사 상한가')),
                ('effective_urgent_price_won', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='적용 급매 기준가')),
                ('first_seen_at', models.DateTimeField(verbose_name='최초 확인 시각')),
                ('last_seen_at', models.DateTimeField(db_index=True, verbose_name='최근 확인 시각')),
                ('active', models.BooleanField(default=True, verbose_name='현재 노출')),
                ('last_urgent_alert_price_won', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='마지막 급매 알림 가격')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='properties.searchcondition', verbose_name='검색 조건')),
            ],
            options={
                'verbose_name': '조건 충족 매물',
                'verbose_name_plural': '조건 충족 매물',
                'ordering': ('price_won', 'floor', 'listing_id'),
                'indexes': [models.Index(fields=['condition', 'active'], name='properties__conditi_64e003_idx')],
                'constraints': [models.UniqueConstraint(fields=('condition', 'listing_id'), name='unique_listing_per_condition')],
            },
        ),
    ]
