# Generated by Django 5.2.17 on 2026-09-03 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='observation',
            constraint=models.UniqueConstraint(fields=('scan', 'condition', 'listing_id'), name='unique_observation_per_scan_condition'),
        ),
        migrations.AddConstraint(
            model_name='scan',
            constraint=models.UniqueConstraint(fields=('started_at',), name='unique_scan_started_at'),
        ),
    ]
