# Generated by Django 5.2.17 on 2026-09-03 06:07

from django.db import migrations, models


GWACHEON = "과천"
GWANGGYO = "광교"

# The regions of the six seeded conditions. A condition added later gets its
# region from the YAML seed or from Django admin, not from here.
SEEDED_REGIONS = {
    "raemian-central-suite-84": GWACHEON,
    "gwacheon-central-park-prugio-summit-84": GWACHEON,
    "gwacheon-weverfield-84": GWACHEON,
    "raemian-sur-all": GWACHEON,
    "raemian-eco-palace-all": GWACHEON,
    "gwanggyo-prugio-worldmark-84-85": GWANGGYO,
}

# Kept in step with properties.matching.EXCLUSION_CODES. Duplicated on purpose:
# a migration must not change meaning when that module is later reworded.
REASON_PREFIXES = (
    ("단지명 불일치", "complex"),
    ("면적 미달", "area"),
    ("면적 초과", "area"),
    ("타입 제외", "type"),
    ("층 해석 실패", "floor"),
    ("가격 초과", "price"),
)


def backfill(apps, schema_editor):
    SearchCondition = apps.get_model("properties", "SearchCondition")
    Observation = apps.get_model("properties", "Observation")

    for condition_id, region in SEEDED_REGIONS.items():
        SearchCondition.objects.filter(id=condition_id).update(region=region)

    for prefix, code in REASON_PREFIXES:
        Observation.objects.filter(exclusion_reason__startswith=prefix).update(
            exclusion_code=code
        )

    # Anything excluded for a reason this mapping does not know would silently
    # join the statistics population, so name it rather than let it pass.
    stranded = (
        Observation.objects.exclude(exclusion_reason="")
        .filter(exclusion_code="")
        .count()
    )
    if stranded:
        Observation.objects.exclude(exclusion_reason="").filter(
            exclusion_code=""
        ).update(exclusion_code="other")
        print(f"  분류하지 못한 제외 사유 {stranded}건을 'other'로 표시했습니다.")


def unbackfill(apps, schema_editor):
    """No-op: the reverse migration drops both columns anyway."""


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_observation_unique_observation_per_scan_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='exclusion_code',
            field=models.CharField(blank=True, choices=[('', '조건 충족'), ('complex', '단지명 불일치'), ('area', '면적'), ('type', '타입'), ('floor', '층 해석 실패'), ('price', '가격 초과')], db_index=True, max_length=16, verbose_name='제외 구분'),
        ),
        migrations.AddField(
            model_name='searchcondition',
            name='region',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='지역'),
        ),
        migrations.RunPython(backfill, unbackfill),
    ]
