# Generated by Django 5.2.17 on 2026-09-03 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_region_and_exclusion_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='building',
            field=models.CharField(blank=True, max_length=50, verbose_name='동'),
        ),
        migrations.AddField(
            model_name='observation',
            name='building',
            field=models.CharField(blank=True, max_length=50, verbose_name='동'),
        ),
    ]
