# Generated by Django 5.2.17 on 2026-09-06 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_listing_building_observation_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='properties.listing', verbose_name='대표 매물'),
        ),
    ]
