# Generated by Django 5.2.17 on 2026-09-05 02:27

import django.db.models.deletion
import portfolio.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetClass',
            fields=[
                ('id', models.SlugField(max_length=40, primary_key=True, serialize=False, verbose_name='분류 ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='이름')),
                ('benchmark_category', models.CharField(blank=True, choices=[('domestic_stock', '국내주식'), ('foreign_stock', '해외주식'), ('bond', '채권'), ('alternative', '대체투자')], max_length=20, verbose_name='국민연금 공통분류')),
                ('display_order', models.PositiveSmallIntegerField(default=100, verbose_name='표시 순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
            ],
            options={
                'verbose_name': '자산분류',
                'verbose_name_plural': '자산분류',
                'ordering': ('display_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='DailyPortfolioMetric',
            fields=[
                ('as_of', models.DateField(primary_key=True, serialize=False, verbose_name='기준일')),
                ('market_value', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='평가액')),
                ('external_flow', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='당일 순외부입금')),
                ('cumulative_external_flow', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='누적 순외부입금')),
                ('investment_pl', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='누적 투자손익')),
                ('daily_return', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=12, verbose_name='일간 수익률')),
                ('cumulative_return', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=12, verbose_name='누적 수익률')),
                ('index_value', models.DecimalField(decimal_places=8, default=Decimal('1'), max_digits=18, verbose_name='성과지수')),
                ('peak_index', models.DecimalField(decimal_places=8, default=Decimal('1'), max_digits=18, verbose_name='성과지수 고점')),
                ('drawdown', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=12, verbose_name='현재 낙폭')),
                ('max_drawdown', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=12, verbose_name='MDD')),
                ('computed_at', models.DateTimeField(auto_now=True, verbose_name='계산 시각')),
            ],
            options={
                'verbose_name': '일별 성과',
                'verbose_name_plural': '일별 성과',
                'ordering': ('-as_of',),
            },
        ),
        migrations.CreateModel(
            name='InvestmentAccount',
            fields=[
                ('id', models.SlugField(max_length=40, primary_key=True, serialize=False, verbose_name='계좌 ID')),
                ('institution', models.CharField(default='KB증권', max_length=50, verbose_name='금융기관')),
                ('alias', models.CharField(max_length=50, verbose_name='별칭')),
                ('masked_number', models.CharField(blank=True, max_length=40, validators=[portfolio.models._validate_masked_account_number], verbose_name='마스킹 계좌번호')),
                ('account_type', models.CharField(choices=[('brokerage', '종합위탁'), ('isa', 'ISA'), ('pension', '개인연금'), ('retirement', '퇴직연금')], max_length=20, verbose_name='계좌 유형')),
                ('required', models.BooleanField(default=True, verbose_name='완전 수집 필수')),
                ('active', models.BooleanField(default=True, verbose_name='사용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
            ],
            options={
                'verbose_name': '투자 계좌',
                'verbose_name_plural': '투자 계좌',
                'ordering': ('account_type', 'alias'),
            },
        ),
        migrations.CreateModel(
            name='BenchmarkAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of', models.DateField(db_index=True, verbose_name='기준일')),
                ('source_category', models.CharField(max_length=50, verbose_name='원본 분류')),
                ('benchmark_category', models.CharField(choices=[('domestic_stock', '국내주식'), ('foreign_stock', '해외주식'), ('bond', '채권'), ('alternative', '대체투자')], max_length=20, verbose_name='공통분류')),
                ('source_percent', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='원본 비중(%)')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='출처')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
            ],
            options={
                'verbose_name': '국민연금 기준 비중',
                'verbose_name_plural': '국민연금 기준 비중',
                'ordering': ('-as_of', 'source_category'),
                'constraints': [models.UniqueConstraint(fields=('as_of', 'source_category'), name='unique_benchmark_per_date_category')],
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('code', models.SlugField(max_length=40, primary_key=True, serialize=False, verbose_name='종목코드')),
                ('name', models.CharField(max_length=100, verbose_name='종목명')),
                ('currency', models.CharField(default='KRW', max_length=3, verbose_name='통화')),
                ('benchmark_category', models.CharField(blank=True, choices=[('domestic_stock', '국내주식'), ('foreign_stock', '해외주식'), ('bond', '채권'), ('alternative', '대체투자')], max_length=20, verbose_name='국민연금 공통분류 (종목 지정)')),
                ('is_cash', models.BooleanField(default=False, verbose_name='현금성')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('asset_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instruments', to='portfolio.assetclass', verbose_name='자산분류')),
            ],
            options={
                'verbose_name': '종목',
                'verbose_name_plural': '종목',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of', models.DateField(db_index=True, verbose_name='기준일')),
                ('document_type', models.CharField(choices=[('balance', '잔고'), ('cash', '예수금'), ('trade', '거래'), ('transfer', '입출금')], max_length=20, verbose_name='자료 종류')),
                ('file_hash', models.CharField(max_length=64, verbose_name='파일 해시')),
                ('source_name', models.CharField(blank=True, max_length=200, verbose_name='원본 파일명')),
                ('row_count', models.PositiveIntegerField(default=0, verbose_name='행 수')),
                ('status', models.CharField(choices=[('success', '성공'), ('incomplete', '불완전'), ('failed', '실패')], default='success', max_length=20, verbose_name='상태')),
                ('error', models.TextField(blank=True, verbose_name='오류')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='기록 시각')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_runs', to='portfolio.investmentaccount', verbose_name='계좌')),
            ],
            options={
                'verbose_name': '수집 실행',
                'verbose_name_plural': '수집 실행',
                'ordering': ('-as_of', 'account_id', 'document_type'),
            },
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_on', models.DateField(db_index=True, verbose_name='발생일')),
                ('flow_type', models.CharField(choices=[('deposit', '입금'), ('withdrawal', '출금'), ('dividend', '배당'), ('interest', '이자'), ('fee', '수수료'), ('tax', '세금'), ('buy', '매수'), ('sell', '매도'), ('transfer_in', '계좌 간 입고'), ('transfer_out', '계좌 간 출고')], max_length=20, verbose_name='구분')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='금액')),
                ('currency', models.CharField(default='KRW', max_length=3, verbose_name='통화')),
                ('amount_krw', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='원화금액')),
                ('is_external', models.BooleanField(default=False, verbose_name='외부 현금흐름')),
                ('memo', models.CharField(blank=True, max_length=200, verbose_name='메모')),
                ('external_key', models.CharField(max_length=100, verbose_name='원본 키')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='기록 시각')),
                ('import_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_flows', to='portfolio.importrun', verbose_name='수집 실행')),
                ('instrument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_flows', to='portfolio.instrument', verbose_name='종목')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_flows', to='portfolio.investmentaccount', verbose_name='계좌')),
            ],
            options={
                'verbose_name': '현금흐름',
                'verbose_name_plural': '현금흐름',
                'ordering': ('-occurred_on', 'account_id', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PortfolioTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(db_index=True, verbose_name='적용 시작일')),
                ('target_percent', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='목표 비중(%)')),
                ('active', models.BooleanField(default=True, verbose_name='사용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('asset_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='targets', to='portfolio.assetclass', verbose_name='자산분류')),
            ],
            options={
                'verbose_name': '목표 비중',
                'verbose_name_plural': '목표 비중',
                'ordering': ('-effective_from', 'asset_class_id'),
            },
        ),
        migrations.CreateModel(
            name='PositionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of', models.DateField(db_index=True, verbose_name='기준일')),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='보유수량')),
                ('average_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='평균단가')),
                ('cost_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='매입금액')),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='현재가')),
                ('market_value', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='평가금액')),
                ('unrealized_pl', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='평가손익')),
                ('currency', models.CharField(default='KRW', max_length=3, verbose_name='통화')),
                ('market_value_krw', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='원화평가액')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='portfolio.investmentaccount', verbose_name='계좌')),
                ('import_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='portfolio.importrun', verbose_name='수집 실행')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='portfolio.instrument', verbose_name='종목')),
            ],
            options={
                'verbose_name': '보유 스냅샷',
                'verbose_name_plural': '보유 스냅샷',
                'ordering': ('-as_of', 'account_id', 'instrument_id'),
            },
        ),
        migrations.AddConstraint(
            model_name='importrun',
            constraint=models.UniqueConstraint(fields=('account', 'document_type', 'as_of'), name='unique_import_per_account_document_date'),
        ),
        migrations.AddConstraint(
            model_name='importrun',
            constraint=models.UniqueConstraint(fields=('account', 'document_type', 'file_hash'), name='unique_import_per_account_document_hash'),
        ),
        migrations.AddIndex(
            model_name='cashflow',
            index=models.Index(fields=['occurred_on', 'account'], name='portfolio_c_occurre_cc354d_idx'),
        ),
        migrations.AddConstraint(
            model_name='cashflow',
            constraint=models.UniqueConstraint(fields=('account', 'external_key'), name='unique_cash_flow_per_account_key'),
        ),
        migrations.AddConstraint(
            model_name='portfoliotarget',
            constraint=models.UniqueConstraint(fields=('effective_from', 'asset_class'), name='unique_target_per_date_asset_class'),
        ),
        migrations.AddConstraint(
            model_name='portfoliotarget',
            constraint=models.CheckConstraint(condition=models.Q(('target_percent__gte', 0), ('target_percent__lte', 100)), name='target_percent_within_range'),
        ),
        migrations.AddIndex(
            model_name='positionsnapshot',
            index=models.Index(fields=['as_of', 'account'], name='portfolio_p_as_of_04f084_idx'),
        ),
        migrations.AddConstraint(
            model_name='positionsnapshot',
            constraint=models.UniqueConstraint(fields=('as_of', 'account', 'instrument'), name='unique_position_per_day_account_instrument'),
        ),
    ]
