# Generated by Django 5.2.17 on 2026-09-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='code',
            field=models.SlugField(allow_unicode=True, max_length=40, primary_key=True, serialize=False, verbose_name='종목코드'),
        ),
    ]
