# Generated by Django 5.2.17 on 2026-09-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_instrument_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='수량'),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='단가'),
        ),
    ]
