# Generated by Django 5.2.17 on 2026-09-06 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_cashflow_quantity_cashflow_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='price_source',
            field=models.CharField(blank=True, max_length=64, verbose_name='시세 출처'),
        ),
        migrations.CreateModel(
            name='ManualHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='보유수량')),
                ('cost_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='매입금액')),
                ('active', models.BooleanField(default=True, verbose_name='사용')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='메모')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_holdings', to='portfolio.investmentaccount', verbose_name='계좌')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_holdings', to='portfolio.instrument', verbose_name='종목')),
            ],
            options={
                'verbose_name': '직접 입력 보유',
                'verbose_name_plural': '직접 입력 보유',
                'ordering': ('account_id', 'instrument_id'),
                'constraints': [models.UniqueConstraint(fields=('account', 'instrument'), name='unique_manual_holding')],
            },
        ),
    ]
