# Generated by Django 5.2.17 on 2026-09-09 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_hableaccountdailymetric'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentDailyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of', models.DateField(db_index=True, verbose_name='기준일')),
                ('close', models.DecimalField(decimal_places=8, max_digits=24, verbose_name='종가')),
                ('source', models.CharField(max_length=64, verbose_name='시세 출처')),
                ('fetched_at', models.DateTimeField(auto_now=True, verbose_name='수집 시각')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_prices', to='portfolio.instrument', verbose_name='종목')),
            ],
            options={
                'verbose_name': '종목 일 종가',
                'verbose_name_plural': '종목 일 종가',
                'ordering': ('-as_of', 'instrument_id'),
                'constraints': [models.UniqueConstraint(fields=('as_of', 'instrument'), name='unique_daily_price_per_instrument')],
            },
        ),
    ]
