# Generated by Django 5.2.17 on 2026-09-10 11:33

import django.db.models.deletion
import spending.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpendingCategory',
            fields=[
                ('id', models.SlugField(max_length=40, primary_key=True, serialize=False, verbose_name='코드')),
                ('name', models.CharField(max_length=40, verbose_name='이름')),
                ('order', models.PositiveSmallIntegerField(default=100, verbose_name='정렬')),
                ('is_financial_cost', models.BooleanField(default=False, help_text='연회비·이자가 자동으로 들어갈 카테고리', verbose_name='금융비용')),
            ],
            options={
                'verbose_name': '소비 카테고리',
                'verbose_name_plural': '소비 카테고리',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_month', models.CharField(max_length=7, unique=True, validators=[spending.models.validate_billing_month], verbose_name='청구월')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='결제일')),
                ('total_billed_won', models.BigIntegerField(verbose_name='청구총액')),
                ('source_ref', models.CharField(blank=True, max_length=200, verbose_name='원본 메일')),
                ('parsed_at', models.DateTimeField(blank=True, null=True, verbose_name='파싱 시각')),
                ('received_at', models.DateTimeField(auto_now=True, verbose_name='수신 시각')),
                ('digest_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='카카오 발송')),
            ],
            options={
                'verbose_name': '명세서',
                'verbose_name_plural': '명세서',
                'ordering': ('-billing_month',),
            },
        ),
        migrations.CreateModel(
            name='MerchantRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=80, unique=True, verbose_name='키워드')),
                ('order', models.PositiveSmallIntegerField(default=100, help_text='작을수록 먼저 검사한다', verbose_name='우선순위')),
                ('note', models.CharField(blank=True, max_length=120, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='spending.spendingcategory', verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '가맹점 규칙',
                'verbose_name_plural': '가맹점 규칙',
                'ordering': ('order', '-keyword'),
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateField(verbose_name='이용일')),
                ('merchant', models.CharField(max_length=200, verbose_name='가맹점')),
                ('merchant_norm', models.CharField(db_index=True, max_length=200, verbose_name='정규화명')),
                ('billed_won', models.BigIntegerField(help_text='취소는 음수', verbose_name='청구액')),
                ('total_won', models.BigIntegerField(verbose_name='원 이용금액')),
                ('payment_type', models.CharField(choices=[('lump', '일시불'), ('installment', '할부'), ('cash_advance', '현금서비스'), ('overseas', '해외'), ('annual_fee', '연회비'), ('interest', '이자'), ('other', '기타')], default='lump', max_length=20, verbose_name='결제유형')),
                ('installment_seq', models.PositiveSmallIntegerField(default=0, verbose_name='할부 회차')),
                ('installment_months', models.PositiveSmallIntegerField(default=0, verbose_name='할부 개월')),
                ('card_last4', models.CharField(blank=True, max_length=4, verbose_name='카드 뒤 4자리')),
                ('category_source', models.CharField(blank=True, choices=[('rule', '규칙'), ('payment_type', '결제유형'), ('manual', '직접 지정'), ('', '미분류')], max_length=20, verbose_name='분류 근거')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='spending.spendingcategory', verbose_name='카테고리')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='spending.statement', verbose_name='명세서')),
            ],
            options={
                'verbose_name': '거래',
                'verbose_name_plural': '거래',
                'ordering': ('-used_at', '-billed_won'),
                'indexes': [models.Index(fields=['statement', 'category'], name='spending_tr_stateme_035d6c_idx'), models.Index(fields=['used_at'], name='spending_tr_used_at_8c384c_idx')],
            },
        ),
    ]
