# Generated by Django 5.2.17 on 2026-09-10 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spending', '0002_seed_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpendingGroup',
            fields=[
                ('id', models.SlugField(max_length=40, primary_key=True, serialize=False, verbose_name='코드')),
                ('name', models.CharField(max_length=40, verbose_name='이름')),
                ('order', models.PositiveSmallIntegerField(default=100, verbose_name='정렬')),
                ('color', models.CharField(default='#94a3b8', help_text='#rrggbb', max_length=7, verbose_name='색')),
                ('note', models.CharField(blank=True, max_length=120, verbose_name='설명')),
            ],
            options={
                'verbose_name': '대분류',
                'verbose_name_plural': '대분류',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.AddField(
            model_name='spendingcategory',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='spending.spendinggroup', verbose_name='대분류'),
        ),
    ]
