# Generated by Django 5.2.17 on 2026-09-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spending', '0004_seed_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='excluded',
            field=models.BooleanField(default=False, help_text='체크하면 분석에서 빼지만 명세서 대조에는 남는다', verbose_name='집계 제외'),
        ),
    ]
