# Generated by Django 5.2.17 on 2026-09-10 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spending', '0008_narrow_mall_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_last4', models.CharField(max_length=4, unique=True, verbose_name='카드 뒤 4자리')),
                ('name', models.CharField(max_length=50, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '카드 사용자',
                'verbose_name_plural': '카드 사용자',
                'ordering': ('name', 'card_last4'),
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='note',
            field=models.CharField(blank=True, max_length=15, verbose_name='메모'),
        ),
    ]
